version: 2.1

orbs:
  # https://circleci.com/orbs/registry/orb/circleci/docker-publish
  docker-publish: circleci/docker-publish@0.1.3
workflows:

  # This workflow will be run on all branches but master (to test)
  build_without_publishing_job:
    jobs:
      - docker-publish/publish:
          image: vanessa/scif-go
	  dockerfile: docker/Dockerfile
          deploy: false
          tag: latest
          filters:
            branches:
              ignore: 
                - master
                - docs*
          after_build:
            - run:
                name: Preview Docker Tag for Build
                command: |
                   DOCKER_TAG=$(docker run vanessa/scif-go:latest version)
                   echo "Version for Docker tag is ${DOCKER_TAG}"

      - docker-publish/publish:
          image: vanessa/scif-go
	  dockerfile: docker/Dockerfile.hello-world
          deploy: false
          tag: hello-world
          filters:
            branches:
              ignore: 
                - master
                - docs*
          after_build:
            - run:
                name: Preview Docker Tag for Build
                command: |
                   DOCKER_TAG=$(docker run vanessa/scif-go:hello-world version)
                   echo "Version for Docker tag is hello-world-${DOCKER_TAG}"

  # This workflow will deploy images on merge to master only
  docker_with_lifecycle:
    jobs:
      - docker-publish/publish:
          image: vanessa/scif-go
	  dockerfile: docker/Dockerfile
          tag: latest
          filters:
            branches:
             only: master
          after_build:
            - run:
                name: Publish Docker Tag with SCIF Version
                command: |
                   DOCKER_TAG=$(docker run vanessa/scif-go:latest version)
                   echo "Version for Docker tag is ${DOCKER_TAG}"
                   docker tag vanessa/scif-go:latest vanessa/scif-go:${DOCKER_TAG}

      - docker-publish/publish:
          image: vanessa/scif-go
	  dockerfile: docker/Dockerfile.hello-world
          tag: hello-world
          filters:
            branches:
              ignore: 
                - master
                - docs*
          after_build:
            - run:
                name: Publish Docker Tag with SCIF Version
                command: |
                   DOCKER_TAG=$(docker run vanessa/scif-go:hello-world version)
                   echo "Version for Docker tag is hello-world-${DOCKER_TAG}"
                   docker tag vanessa/scif-go:hello-world vanessa/scif-go:hello-world-${DOCKER_TAG}
