FROM iron/go:dev as builder

# alpine image with the go tools
# docker build -t vanessa/scif-go .

WORKDIR /code
ENV SRC_DIR=/go/src/github.com/sci-f/scif-go
ADD . $SRC_DIR
WORKDIR $SRC_DIR

# Dependencies
ENV SCIF_SHELL /bin/sh
RUN make deps && \
    make build && \
    cp bin/scif /usr/local/bin

ENTRYPOINT ["/usr/local/bin/scif"]
